Change test pipeline

diff --git a/.github/workflows/prt-test.yml b/.github/workflows/prt-test.yml
--- a/.github/workflows/prt-test.yml
+++ b/.github/workflows/prt-test.yml
@@ -1,52 +1,65 @@
 name: CI Test for PRs
 
 on:
-  pull_request:
-    branches:
-      - main
+    pull_request:
+        branches:
+            - main
 
 jobs:
-  test:
-    runs-on: ubuntu-latest
+    test:
+        runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+        steps:
+            -   name: Checkout code
+                uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+            -   name: Set up Docker Buildx
+                uses: docker/setup-buildx-action@v3
 
-      - name: Login to DockerHub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+            -   name: Login to DockerHub
+                uses: docker/login-action@v3
+                with:
+                    username: ${{ secrets.DOCKER_USERNAME }}
+                    password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build Strapi and Next.js images
-        run: |
-          docker buildx build --platform linux/amd64 \
-            -t portefolio-strapi:test \
-            -f ./docker/strapi/Dockerfile \
-            --load .
-          docker buildx build --platform linux/amd64 \
-            -t portefolio-nextjs:test \
-            -f ./docker/nextjs/Dockerfile \
-            --load .
+            -   name: Build Strapi and Next.js images
+                run: |
+                    docker buildx build --platform linux/amd64 \
+                      -t portefolio-strapi:test \
+                      -f ./docker/strapi/Dockerfile \
+                      --load .
+                    docker buildx build --platform linux/amd64 \
+                      -t portefolio-nextjs:test \
+                      -f ./docker/nextjs/Dockerfile \
+                      --load .
 
-      - name: Start services with Docker Compose
-        run: |
-          docker compose -f docker-compose.ci.yml up -d
+            -   name: Start services with Docker Compose
+                run: |
+                    docker compose -f docker-compose.ci.yml up -d
 
-      - name: Wait for services to be ready
-        run: |
-          echo "Waiting for services to start..."
-          sleep 10  # Attendre quelques secondes pour laisser Strapi et Next.js démarrer
-          docker ps
+            -   name: Wait for services to be ready
+                run: |
+                    echo "Waiting for services to start..."
+                    sleep 10  # Attendre quelques secondes pour laisser Strapi et Next.js démarrer
+                    docker ps
 
-      - name: Run Playwright tests inside Docker
-        run: |
-          docker compose -f docker-compose.ci.yml up tests --exit-code-from tests
+            -   name: Run Playwright tests inside Next.js container
+                id: tests
+                run: |
+                    docker exec portefolio-nextjs-1 npx playwright test
+                    
+                    # Copier les résultats des tests
+                    mkdir -p playwright-report
+                    docker cp portefolio-nextjs-1:/app/playwright-report ./playwright-report || echo "No report found"
+                    
+                    # Lire les résultats et extraire le nombre de tests échoués
+                    if [ -f ./playwright-report/result.txt ]; then
+                      export count=$(grep "Failed" ./playwright-report/result.txt | cut -d ':' -f 2 | tr -d ' ')
+                    else
+                      export count="0"
+                    fi
+                    echo "fail_count=$count" >> "$GITHUB_OUTPUT"
 
-      - name: Stop and clean up
-        run: |
-          docker compose -f docker-compose.ci.yml down -v
+            -   name: Stop and clean up
+                run: |
+                    docker compose -f docker-compose.ci.yml down -v
